spring.application.name=secrest
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/ms_user?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=020804
spring.jpa.hibernate.ddl-auto=update